defaults: &defaults
  autocomplete: true
  label: true
searches: &searches
  method: get
  placeholder: true
  autofilter: true
default:
  <<: *defaults
  origin:
    label: label
    offset: field-label
    input: input
    textarea: field textarea
    submit: button is-primary
    inline_checkbox: checkbox
    inline_checkbox_checked: checkbox
    inline_radio: radio
    inline_radio_checked: radio
  offset:
    submit: field-label
  wrap:
    all: field is-horizontal
    all_required: field is-horizontal
    all_error: field is-horizontal
    label: field-label is-normal
    input: field-body > field > control
    select: field-body > field is-narrow > control > select is-fullwidth
    checkbox: field-body > field > control > checkbox
    checkboxes: field-body > field is-narrow > control
    submit: field-body control
  error:
    input: input is-danger
  label:
    checkboxes: field-label
search:
  <<: *searches
  origin:
    form: field is-horizontal
    input: input
    submit: button is-primary
  wrap:
    input: field is-narrow
weui:
  <<: *defaults
  origin:
    form: weui-form
    label: weui-label
    input: weui-input
    textarea: weui-textarea
    select: weui-select
    muilti_select: weui-select
    submit: weui-btn weui-btn_primary
  wrap:
    all: weui-cell weui-cell_active
    all_error: weui-cell
    all_required: weui-cell
    label: weui-cell__hd
    input: weui-cell__bd
    submit: weui-form__opr-area
weui_search:
  <<: *searches
  origin:
    form: weui-cells weui-cells_form
    label: weui-label
    input: weui-input
    select: weui-select
    muilti_select: weui-select
    submit: weui-btn weui-btn_primary
  wrap:
    all: weui-cell
    all_error: inline field error
    input: weui-cell__bd
    submit: weui-btn-area
