defaults: &defaults
  autocomplete: true
  label: true
searches: &searches
  method: get
  placeholder: true
  autofilter: true
default:
  <<: *defaults
  origin:
    label: label
    input: input
    textarea: field textarea
    submit: button is-primary
    inline_checkbox: checkbox
    inline_checkbox_checked: checkbox
    inline_radio: radio
    inline_radio_checked: radio
  before_wrap:
    submit: field-label
    checkboxes: field-label
    checkbox: field-label
  wrap:
    label: field-label is-normal
    input: field-body > field > control
    select: field-body > field is-narrow > control > select is-fullwidth
    checkbox: field-body > field > control > checkbox
    checkboxes: field-body > field is-narrow > control
    submit: field-body control
  all:
    normal: field is-horizontal
    required: field is-horizontal
    error: field is-horizontal
    submit: field is-horizontal
    select: field is-horizontal
    checkbox: field is-horizontal
  error:
    input: input is-danger
search:
  <<: *searches
  form: field is-horizontal
  origin:
    input: input
    submit: button is-primary
  wrap:
    input: field is-narrow
inline:
  origin:
    input: input
weui:
  <<: *defaults
  form: weui-form
  origin:
    label: weui-label
    input: weui-input
    textarea: weui-textarea
    select: weui-select
    muilti_select: weui-select
    submit: weui-btn weui-btn_primary
    checkbox: weui-check
    radio: weui-check
  wrap:
    label: weui-cell__hd
    input: weui-cell__bd
    select: weui-cell__bd
    checkbox: weui-cell__hd
    radio: weui-cell__ft
  all:
    normal: weui-cell weui-cell_active
    error: weui-cell
    required: weui-cell
    select: weui-cell weui-cell_active weui-cell_select weui-cell_select-after
    checkbox: weui-cell weui-cell_active weui-cell_switch
    radio: weui-cell weui-cell_active weui-cell_radio
    submit: weui-form__opr-area
  after:
    checkbox: <i class="weui-icon-checked"></i>
    radio: <i class="weui-icon-checked"></i>
weui_search:
  <<: *searches
  form: weui-cells weui-cells_form
  origin:
    label: weui-label
    input: weui-input
    select: weui-select
    muilti_select: weui-select
    submit: weui-btn weui-btn_primary
  wrap:
    input: weui-cell__bd
    submit: weui-btn-area
  all:
    normal: weui-cell
    error: weui-cell
