defaults: &defaults
  autocomplete: 'off' # 这里 off 必须字符串，否则会解析为 false
  label: true
origin: &default_origins
  label: label color-grey
  input: input
  textarea: textarea
  inline_checkbox: checkbox
  inline_checkbox_checked: checkbox
  inline_radio: radio
  inline_radio_checked: radio
wrap: &default_wraps
  input: field-body > field > control
  select: field-body > field is-narrow > control > select is-fullwidth
  checkbox: field-body > field > control > checkbox
  radios: field-body > field > control > checkbox
  checkboxes: field-body > field is-narrow > control
wrap_label: &default_wrap_labels
  normal: field-label is-normal
  select: field-label is-normal
  checkbox: field-label is-normal
  checkboxes: field-label
all: &default_alls
  normal: field is-horizontal
  required: field is-horizontal
  error: field is-horizontal
  select: field is-horizontal
  checkbox: field is-horizontal
error: &default_errors
  input: input is-danger
before_wrap: &default_before_wraps
  checkboxes: field-label
  checkbox: field-label
searches: &searches
  method: get
  placeholder: true
  autofilter: true
  autocomplete: 'off'
phone: &phone
  <<: *defaults
phone_wrap: &phone_wrap
  input: control
  select: control > select is-fullwidth
phone_all: &phone_all
  normal: field
  error: field
  required: field
  select: field
  checkbox: weui-cell weui-cell_active weui-cell_switch
  radio: weui-cell weui-cell_active weui-cell_radio
default:
  <<: *defaults
  origin:
    <<: *default_origins
    label: label
    textarea: field textarea
    submit: button is-primary
  before_wrap:
    <<: *default_before_wraps
    submit: field-label
  wrap:
    <<: *default_wraps
    submit: field-body control
  wrap_label:
    <<: *default_wrap_labels
  all:
    <<: *default_alls
    submit: field is-horizontal
  error:
    <<: *default_errors
modal:
  <<: *defaults
  form: modal-card
  origin:
    <<: *default_origins
    submit: button is-medium is-primary
  before_wrap:
    <<: *default_before_wraps
  wrap:
    <<: *default_wraps
    submit: modal-card-foot
  wrap_label:
    <<: *default_wrap_labels
  all:
    <<: *default_alls
  error:
    <<: *default_errors
line:
  <<: *defaults
  origin:
    label: label color-grey
    input: input
    textarea: textarea
    submit: button is-primary
  wrap:
    input: control
  all:
    normal: field
  error:
    <<: *default_errors
weui:
  <<: *defaults
  form: flex flex-direction-column is-fullheight
  origin:
    label: label color-grey
    input: input
    textarea: textarea
    submit: button is-medium is-success is-fullwidth
    checkbox: weui-check
    radio: weui-check
  wrap:
    <<: *phone_wrap
    checkbox: weui-cell__hd
    radio: weui-cell__ft
  all:
    <<: *phone_all
  after:
    checkbox: <i class="weui-icon-checked"></i>
    radio: <i class="weui-icon-checked"></i>
phone_modal:
  <<: *phone
  form: modal-card has-animate-slide-up
  origin:
    <<: *default_origins
    submit: button is-fullwidth is-primary
  wrap:
    <<: *phone_wrap
  all:
    <<: *phone_all
search:
  <<: *searches
  form: field is-horizontal
  origin:
    input: input
    submit: button is-primary
  wrap:
    input: field is-narrow
inline:
  origin:
    input: input
weui_search:
  <<: *searches
  form: weui-cells weui-cells_form
  origin:
    label: weui-label
    input: weui-input
    select: weui-select
    muilti_select: weui-select
    submit: weui-btn weui-btn_primary
  wrap:
    input: weui-cell__bd
    submit: weui-btn-area
  all:
    normal: weui-cell
    error: weui-cell