defaults: &defaults
  autocomplete: off
  label: true
origin: &default_inputs
  label: label color-grey
  input: input
  submit: button is-primary
searches: &searches
  method: get
  placeholder: true
  autofilter: true
phone: &phone
  <<: *defaults
default:
  <<: *defaults
  origin:
    label: label
    textarea: field textarea
    submit: button is-primary
    inline_checkbox: checkbox
    inline_checkbox_checked: checkbox
    inline_radio: radio
    inline_radio_checked: radio
  before_wrap:
    submit: field-label
    checkboxes: field-label
    checkbox: field-label
  wrap:
    label: field-label is-normal
    input: field-body > field > control
    select: field-body > field is-narrow > control > select is-fullwidth
    checkbox: field-body > field > control > checkbox
    checkboxes: field-body > field is-narrow > control
    submit: field-body control
  all:
    normal: field is-horizontal
    required: field is-horizontal
    error: field is-horizontal
    submit: field is-horizontal
    select: field is-horizontal
    checkbox: field is-horizontal
  error:
    input: input is-danger
line:
  <<: *defaults
  origin:
    label: label has-text-grey
    input: input
    textarea: textarea
    submit: button is-primary
  wrap:
    input: control
  all:
    normal: field
weui:
  <<: *defaults
  form: flex flex-direction-column is-fullheight
  origin:
    label: label color-grey
    input: input
    textarea: textarea
    submit: button is-medium is-success is-fullwidth
    checkbox: weui-check
    radio: weui-check
  wrap:
    input: control
    select: control > select
    checkbox: weui-cell__hd
    radio: weui-cell__ft
  all:
    normal: field
    error: field
    required: field
    select: field
    checkbox: weui-cell weui-cell_active weui-cell_switch
    radio: weui-cell weui-cell_active weui-cell_radio
  after:
    checkbox: <i class="weui-icon-checked"></i>
    radio: <i class="weui-icon-checked"></i>
modal:
  <<: *phone
  form: modal-card has-animate-slide-up
  origin:
    <<: *default_inputs
    submit: button is-fullwidth is-primary
search:
  <<: *searches
  form: field is-horizontal
  origin:
    input: input
    submit: button is-primary
  wrap:
    input: field is-narrow
inline:
  origin:
    input: input
weui_search:
  <<: *searches
  form: weui-cells weui-cells_form
  origin:
    label: weui-label
    input: weui-input
    select: weui-select
    muilti_select: weui-select
    submit: weui-btn weui-btn_primary
  wrap:
    input: weui-cell__bd
    submit: weui-btn-area
  all:
    normal: weui-cell
    error: weui-cell